module.exports = {
  purge: {
    mode: "all",
    safelist: [
      "flex",
      "rounded-xl",
      "p-8",
      "p-0",
      "pt-6",
      "p-8",
      "text-center",
      "text-left",
      "space-y-4",
      "text-4xl",
      "font-bold",
      "underline",
      "pl-1",
      "pr-1",
      "text-lg",
      "font-light",
      "font-bold",
      "text-7xl",
      "text-8xl",
      "text-9xl",
      "mt-12",
      "bg-red-500",
      "bg-red-400",
      "font-semibold",
      "text-white",
      "p-2",
      "m-2",
      "border",
      "border-red-500",
      "border-red-400",
      "rounded-md",
      "mt-8",
      "flex-auto",
      "text-xl",
      "bg-blue-400",
      "bg-blue-300",
      "font-semibold",
      "border-blue-400",
      "border-blue-300",
      "blue-500",
      "bg-blue-400",
      "border-blue-500",
      "border-blue-400",
      "pt-32",
      "font-extralight",
      "border-b-2",
    ],

    options: {
      keyframes: true,
    },
  },
  darkMode: false, // or 'media' or 'class'
  theme: {
    extend: {},
  },
  variants: {
    extend: {},
  },
  plugins: [],
};
